import apiClient from './apiClient'

export const adminShoppingService = {
  dashboard: () => apiClient.get('/admin/dashboard'),
  analytics: (params) => apiClient.get('/admin/analytics', { params }),
  reportCsv: (report, params) => apiClient.get(`/admin/reports/${report}/csv`, { params, responseType: 'blob' }),
  products: (params) => apiClient.get('/admin/products', { params }),
  product: (id) => apiClient.get(`/admin/products/${id}`),
  saveProduct: (product) => product.id ? apiClient.put(`/admin/products/${product.id}`, product) : apiClient.post('/admin/products', product),
  removeProduct: (id) => apiClient.delete(`/admin/products/${id}`),
  orders: (params) => apiClient.get('/admin/orders', { params }),
  order: (id) => apiClient.get(`/admin/orders/${id}`),
  transition: (id, payload) => apiClient.post(`/admin/orders/${id}/transition`, payload),
  coupons: (params) => apiClient.get('/admin/coupons', { params }),
  saveCoupon: (coupon) => coupon.id ? apiClient.put(`/admin/coupons/${coupon.id}`, coupon) : apiClient.post('/admin/coupons', coupon),
  removeCoupon: (id) => apiClient.delete(`/admin/coupons/${id}`),
  shippingMethods: (params) => apiClient.get('/admin/shipping-methods', { params }),
  saveShippingMethod: (method) => method.id ? apiClient.put(`/admin/shipping-methods/${method.id}`, method) : apiClient.post('/admin/shipping-methods', method),
  removeShippingMethod: (id) => apiClient.delete(`/admin/shipping-methods/${id}`),
  taxRules: (params) => apiClient.get('/admin/tax-rules', { params }),
  saveTaxRule: (rule) => rule.id ? apiClient.put(`/admin/tax-rules/${rule.id}`, rule) : apiClient.post('/admin/tax-rules', rule),
  removeTaxRule: (id) => apiClient.delete(`/admin/tax-rules/${id}`),
  payments: (params) => apiClient.get('/admin/payments', { params }),
  capture: (id) => apiClient.post(`/admin/payments/${id}/capture`),
  refund: (id, amount) => apiClient.post(`/admin/payments/${id}/refund`, { amount }),
  returns: (params) => apiClient.get('/admin/returns', { params }),
  updateReturn: (id, payload) => apiClient.patch(`/admin/returns/${id}`, payload),
  systemHealth: () => apiClient.get('/admin/system/health'),
  clearCache: () => apiClient.post('/admin/system/cache/clear'),
}
