import { useRef, useState } from 'react'
import { FiCamera, FiExternalLink, FiSearch, FiUpload } from 'react-icons/fi'

const results = [
  { name: 'Draped twill blouse', provider: 'Morrow', price: '$84', image: 'https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=600&q=80' },
  { name: 'Fluid tailored trouser', provider: 'Aster', price: '$92', image: 'https://images.unsplash.com/photo-1506629905607-d405b7a30db6?auto=format&fit=crop&w=600&q=80' },
  { name: 'Soft leather shoulder bag', provider: 'Nomi', price: '$76', image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80' },
]

export default function VisualSearchPage() {
  const input = useRef(); const [file, setFile] = useState(null); const [searched, setSearched] = useState(false); const [provider, setProvider] = useState('All providers')
  const select = (event) => { const image = event.target.files?.[0]; if (image) { setFile(URL.createObjectURL(image)); setSearched(false) } }
  const shown = provider === 'All providers' ? results : results.filter((item) => item.provider === provider)
  return <section className="container py-5 feature-page"><div className="narrow-page text-center mx-auto"><p className="eyebrow">VISUAL SEARCH</p><h1>Show us what you’re looking for.</h1><p className="text-slate-300">Upload an inspiration image and discover similar pieces from our providers.</p><button className={`visual-upload ${file ? 'has-image' : ''}`} onClick={() => input.current.click()}>{file ? <img src={file} alt="Selected inspiration" /> : <><FiCamera /><strong>Drop an image or browse</strong><small>We’ll match silhouette, color, and texture.</small></>}</button><input ref={input} type="file" accept="image/*" hidden onChange={select} /><div className="d-flex justify-content-center gap-2 mt-3"><button className="btn btn-velora-secondary" onClick={() => input.current.click()}><FiUpload /> Upload</button><button className="btn btn-velora-primary" disabled={!file} onClick={() => setSearched(true)}><FiSearch /> Find similar</button></div></div>{searched && <div className="visual-results mt-5"><div className="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><p className="eyebrow mb-1">MATCHES FOUND</p><h2 className="h3 mb-0">Closest visual matches</h2></div><select className="form-select velora-input provider-select" value={provider} onChange={(event) => setProvider(event.target.value)}><option>All providers</option>{[...new Set(results.map((item) => item.provider))].map((item) => <option key={item}>{item}</option>)}</select></div><div className="row g-3">{shown.map((item) => <div className="col-md-4" key={item.name}><article className="velora-card search-result overflow-hidden"><img src={item.image} alt={item.name} /><div className="p-3"><p className="eyebrow mb-1">{item.provider}</p><h3 className="h6">{item.name}</h3><div className="d-flex justify-content-between align-items-center"><strong>{item.price}</strong><button className="btn btn-velora-ghost p-0">View <FiExternalLink /></button></div></div></article></div>)}</div></div>}</section>
}
